version: '3'

services:
  app:
    build: .
    command: yarn dev --host 0.0.0.0
    volumes:
      - ./:/app:cached
    ports:
      - 8080:8080
    environment:
      - API_HOST=http://api:3000
    depends_on:
      - api

  api:
    build: .
    command: yarn serve
    volumes:
      - ./:/app:cached
    environment:
      - REDASH_URL
      - REDASH_API_KEY